# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: icon
cloudProvider: aws

image:
  repo: iconloop/prep-node
  tag: "20210314.0"

node:
  purpose: prep
  runLocal: false
  ports:
    gRPC: 7100
    rpc: 9000
  fastestStart: "\"yes\""
  iconLogLevel: DEBUG
  loopchainLogLevel: DEBUG
  networkEnvironment: mainnet
  endpointURL: ""
  findNeighbor: true
  findNeighborCount: 5
  findNeighborOption: ""
  useNAT: no
  amqpTarget: "127.0.0.1"
  amqpKey: ""
  useExternalMQ: false
  healthCheckInterval: 30
  useSlack: no
  slackURL: ""
  slackPrefix: ""

  certificate:
    autoGenerate: true
    contents: |-
      -----BEGIN EC PRIVATE KEY-----
      ... your key contents ...
      -----END EC PRIVATE KEY-----
    password: password123

deployment:
  replicas: 1
  annotations: null
  resources: {}
#  requests:
#    memory: "5Gi"
#    cpu: "1.5"
  storage:
    storageClassName: ebs-sc
    dataSize: 360Gi
    accessModes: [ "ReadWriteOnce" ]
