# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: icon

image:
  repo: iconloop/icon-node
  tag: 2009031457xdaf395

node:
  purpose: prep
  runLocal: false
  ports:
    gRPC: 7100
    rpc: 9000
  fastestStart: "\"yes\""
  iconLogLevel: DEBUG
  loopchainLogLevel: DEBUG
  networkEnvironment: mainnet
  certificate:
    autoGenerate: true
    contents: |-
      -----BEGIN EC PRIVATE KEY-----
      ... your key contents ...
      -----END EC PRIVATE KEY-----
    password: password123

deployment:
  replicas: 1
  resources: {}
#  requests:
#    memory: "5Gi"
#    cpu: "1.5"
  storage:
    dataSize: 360Gi
    accessModes: [ "ReadWriteOnce" ]